package com.tevonetwork.tevoapi.Core;

import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

public enum Items {

	STONE("stone", new ItemStack(Material.STONE)),
	GRANITE("granite", new ItemStack(Material.STONE, 1, (short)1)),
	POLISHEDGRANITE("polishedgranite", new ItemStack(Material.STONE, 1, (short)2)),
	DIORITE("diorite", new ItemStack(Material.STONE, 1, (short)3)),
	POLISHEDDIORITE("polisheddiorite", new ItemStack(Material.STONE, 1, (short)4)),
	GRASSBLOCK("grass", new ItemStack(Material.GRASS)),
	DIRT("dirt", new ItemStack(Material.DIRT)),
	COARSEDIRT("coarsedirt", new ItemStack(Material.DIRT, 1, (short)1)),
	PODZOL("podzol", new ItemStack(Material.DIRT, 1, (short)2)),
	COBBLESTONE("cobble", new ItemStack(Material.COBBLESTONE)),
	OAKWOODPLANK("oakplanks", new ItemStack(Material.WOOD)),
	SPRUCEWOODPLANK("spruceplanks", new ItemStack(Material.WOOD, 1, (short)1)),
	BIRCHWOODPLANK("birchplanks", new ItemStack(Material.WOOD, 1, (short)2)),
	JUNGLEWOODPLANK("jungleplanks", new ItemStack(Material.WOOD, 1, (short)3)),
	ACACIAWOODPLANK("acaciaplanks", new ItemStack(Material.WOOD, 1, (short)4)),
	DARKOAKWOODPLANK("darkoakplanks", new ItemStack(Material.WOOD, 1, (short)5)),
	OAKSAPLING("oaksapling", new ItemStack(Material.SAPLING)),
	SPRUCESAPLING("sprucesapling", new ItemStack(Material.SAPLING, 1, (short)1)),
	BIRCHSAPLING("birchsapling", new ItemStack(Material.SAPLING, 1, (short)2)),
	JUNGLESAPLING("junglesapling", new ItemStack(Material.SAPLING, 1, (short)3)),
	ACACIASAPLING("acaciasapling", new ItemStack(Material.SAPLING, 1, (short)4)),
	DARKOAKSAPLING("sarkoaksapling", new ItemStack(Material.SAPLING, 1, (short)5)),
	BEDROCK("bedrock", new ItemStack(Material.BEDROCK)),
	WATER("water", new ItemStack(Material.WATER_BUCKET)),
	LAVA("lava", new ItemStack(Material.LAVA_BUCKET)),
	SAND("sand", new ItemStack(Material.SAND)),
	REDSAND("redsand", new ItemStack(Material.SAND, 1, (short)1)),
	GRAVEL("gravel", new ItemStack(Material.GRAVEL)),
	GOLDORE("goldore", new ItemStack(Material.GOLD_ORE)),
	IRONORE("ironore", new ItemStack(Material.IRON_ORE)),
	COALORE("coalore", new ItemStack(Material.COAL_ORE)),
	OAKWOOD("oak", new ItemStack(Material.LOG)),
	SPRUCEWOOD("spruce", new ItemStack(Material.LOG, 1, (short)1)),
	BIRCHWOOD("birch", new ItemStack(Material.LOG, 1, (short)2)),
	JUNGLEWOOD("jungle", new ItemStack(Material.LOG, 1, (short)3)),
	OAKLEAVES("oakleaves", new ItemStack(Material.LEAVES)),
	SPRUCELEAVES("spruceleaves", new ItemStack(Material.LEAVES, 1, (short)1)),
	BIRCHLEAVES("birchleaves", new ItemStack(Material.LEAVES, 1, (short)2)),
	JUNGLELEAVES("jungleleaves", new ItemStack(Material.LEAVES, 1, (short)3)),
	SPONGE("sponge", new ItemStack(Material.SPONGE)),
	WETSPONGE("wetsponge", new ItemStack(Material.SPONGE, 1, (short)1)),
	GLASS("glass", new ItemStack(Material.GLASS)),
	LAPISLAZULIORE("lapisore", new ItemStack(Material.LAPIS_ORE)),
	LAPISLAZULIBLOCK("lapisblock", new ItemStack(Material.LAPIS_BLOCK)),
	DISPENSER("dispenser", new ItemStack(Material.DISPENSER)),
	SANDSTONE("sandstone", new ItemStack(Material.SANDSTONE)),
	CHISELEDSANDSTONE("chiseledsandstone", new ItemStack(Material.SANDSTONE, 1, (short)1)),
	SMOOTHSANDSTONE("smoothsandstone", new ItemStack(Material.SANDSTONE, 1, (short)2)),
	NOTEBLOCK("noteblock", new ItemStack(Material.NOTE_BLOCK)),
	BED("bed", new ItemStack(Material.BED)),
	POWEREDRAIL("poweredrail", new ItemStack(Material.POWERED_RAIL)),
	DETECTORRAIL("detectorrail", new ItemStack(Material.DETECTOR_RAIL)),
	STICKYPISTON("stickypiston", new ItemStack(Material.PISTON_STICKY_BASE)),
	WEB("web", new ItemStack(Material.WEB)),
	DEADSHRUB("shrub", new ItemStack(Material.LONG_GRASS)),
	GRASS("longgrass", new ItemStack(Material.LONG_GRASS, 1, (short)1)),
	FERN("fern", new ItemStack(Material.LONG_GRASS, 1, (short)2)),
	DEADBUSH("deadbush", new ItemStack(Material.LONG_GRASS)),
	PISTON("piston", new ItemStack(Material.PISTON_BASE)),
	WOOL("wool", new ItemStack(Material.WOOL)),
	ORANGEWOOL("orangewool", new ItemStack(Material.WOOL, 1, (short)1)),
	MAGENTAWOOL("magentawool", new ItemStack(Material.WOOL, 1, (short)2)),
	LIGHTBLUEWOOL("lightbluewool", new ItemStack(Material.WOOL, 1, (short)3)),
	YELLOWOOL("yellowwool", new ItemStack(Material.WOOL, 1, (short)4)),
	LIMEWOOL("linewool", new ItemStack(Material.WOOL, 1, (short)5)),
	PINKWOOL("pinkwool", new ItemStack(Material.WOOL, 1, (short)6)),
	GRAYWOOL("greywool", new ItemStack(Material.WOOL, 1, (short)7)),
	LIGHTGRAYWOOL("lightgreywool", new ItemStack(Material.WOOL, 1, (short)8)),
	CYANWOOL("cyanwool", new ItemStack(Material.WOOL, 1, (short)9)),
	PURPLEWOOL("purplewool", new ItemStack(Material.WOOL, 1, (short)10)),
	BLUEWOOL("bluewool", new ItemStack(Material.WOOL, 1, (short)11)),
	BROWNWOOL("brownwool", new ItemStack(Material.WOOL, 1, (short)12)),
	GREENWOOL("greenwool", new ItemStack(Material.WOOL, 1, (short)13)),
	REDWOOL("redwool", new ItemStack(Material.WOOL, 1, (short)14)),
	BLACKWOOL("blackwool", new ItemStack(Material.WOOL, 1, (short)15)),
	DANDELION("dandelion", new ItemStack(Material.YELLOW_FLOWER)),
	POPPY("poppy", new ItemStack(Material.RED_ROSE)),
	BLUEORCHID("blueorchid", new ItemStack(Material.RED_ROSE, 1, (short)1)),
	ALLIUM("allium", new ItemStack(Material.RED_ROSE, 1, (short)2)),
	AZUREBLUET("azurebluet", new ItemStack(Material.RED_ROSE, 1, (short)3)),
	REDTULIP("redtulip", new ItemStack(Material.RED_ROSE, 1, (short)4)),
	ORANGETULIP("orangetulip", new ItemStack(Material.RED_ROSE, 1, (short)5)),
	WHITETULIP("whitetulip", new ItemStack(Material.RED_ROSE, 1, (short)6)),
	PINKTULIP("pinktulip", new ItemStack(Material.RED_ROSE, 1, (short)7)),
	OXEYEDAISY("oxeyedaisy", new ItemStack(Material.RED_ROSE, 1, (short)8)),
	BROWNMUSHROOM("brownmushroom", new ItemStack(Material.BROWN_MUSHROOM)),
	MUSHROOM("mushroom", new ItemStack(Material.RED_MUSHROOM)),
	GOLDBLOCK("goldblock", new ItemStack(Material.GOLD_BLOCK)),
	IRONBLOCK("ironblock", new ItemStack(Material.IRON_BLOCK)),
	STONESLAB("slab", new ItemStack(Material.STEP)),
	SANDSTONESLAB("sandstoneslab", new ItemStack(Material.STEP, 1, (short)1)),
	COBBLESTONESLAB("cobbleslab", new ItemStack(Material.STEP, 1, (short)3)),
	BRICKSLAB("brickslab", new ItemStack(Material.STEP, 1, (short)4)),
	STONEBRICKSLAB("stonebrickslab", new ItemStack(Material.STEP, 1, (short)5)),
	NETHERBRICKSLAB("netherslab", new ItemStack(Material.STEP, 1, (short)6)),
	QUARTZSLAB("quartzslab", new ItemStack(Material.STEP, 1, (short)7)),
	BRICKS("brick", new ItemStack(Material.BRICK)),
	TNT("tnt", new ItemStack(Material.TNT)),
	BOOKSHELF("bookshelf", new ItemStack(Material.BOOKSHELF)),
	MOSSSTONE("mossycobble", new ItemStack(Material.MOSSY_COBBLESTONE)),
	OBSIDIAN("obsidian", new ItemStack(Material.OBSIDIAN)),
	TORCH("torch", new ItemStack(Material.TORCH)),
	SPAWNER("spawner", new ItemStack(Material.MOB_SPAWNER)),
	OAKWOODSTAIRS("oakstairs", new ItemStack(Material.WOOD_STAIRS)),
	CHEST("chest", new ItemStack(Material.CHEST)),
	DIAMONDORE("diamondore", new ItemStack(Material.DIAMOND_ORE)),
	DIAMONDBLOCK("diamondblock", new ItemStack(Material.DIAMOND_BLOCK)),
	CRAFTINGTABLE("workbench", new ItemStack(Material.WORKBENCH)),
	FURNACE("furnace", new ItemStack(Material.FURNACE)),
	LADDER("ladder", new ItemStack(Material.LADDER)),
	RAIL("rail", new ItemStack(Material.RAILS)),
	COBBLESTONESTAIRS("cobblestairs", new ItemStack(Material.COBBLESTONE_STAIRS)),
	LEVER("lever", new ItemStack(Material.LEVER)),
	STONEPRESSUREPLATE("pressureplate", new ItemStack(Material.STONE_PLATE)),
	WOODENPRESSUREPLATE("woodpressureplate", new ItemStack(Material.WOOD_PLATE)),
	REDSTONEORE("redstoneore", new ItemStack(Material.REDSTONE_ORE)),
	STONEBUTTON("button", new ItemStack(Material.STONE_BUTTON)),
	SNOW("snow", new ItemStack(Material.SNOW)),
	ICE("ice", new ItemStack(Material.ICE)),
	SNOWBLOCK("snowblock", new ItemStack(Material.SNOW_BLOCK)),
	CACTUS("cactus", new ItemStack(Material.CACTUS)),
	CLAY("clayblock", new ItemStack(Material.CLAY)),
	SUGARCANE("sugarcane", new ItemStack(Material.SUGAR_CANE)),
	JUKEBOX("jukebox", new ItemStack(Material.JUKEBOX)),
	OAKFENCE("fence", new ItemStack(Material.FENCE)),
	PUMPKIN("pumpkin", new ItemStack(Material.PUMPKIN)),
	NETHERRACK("netherrack", new ItemStack(Material.NETHERRACK)),
	SOULSAND("soulsand", new ItemStack(Material.SOUL_SAND)),
	GLOWSTONE("glowstone", new ItemStack(Material.GLOWSTONE)),
	PORTAL("portal", new ItemStack(Material.PORTAL)),
	JACKOLANTERN("lantern", new ItemStack(Material.JACK_O_LANTERN)),
	WHITESTAINEDGLASS("stainedglass", new ItemStack(Material.STAINED_GLASS)),
	ORANGESTAINEDGLASS("orangeglass", new ItemStack(Material.STAINED_GLASS, 1, (short)1)),
	MAGENTASTAINEDGLASS("magentaglass", new ItemStack(Material.STAINED_GLASS, 1, (short)2)),
	LIGHTBLUESTAINEDGLASS("lightblueglass", new ItemStack(Material.STAINED_GLASS, 1, (short)3)),
	YELLOWSTAINEDGLASS("yellowglass", new ItemStack(Material.STAINED_GLASS, 1, (short)4)),
	LIMESTAINEDGLASS("limeglass", new ItemStack(Material.STAINED_GLASS, 1, (short)5)),
	PINKSTAINEDGLASS("pinkglass", new ItemStack(Material.STAINED_GLASS, 1, (short)6)),
	GRAYSTAINEDGLASS("greyglass", new ItemStack(Material.STAINED_GLASS, 1, (short)7)),
	LIGHTGRAYSTAINEDGLASS("lightgreyglass", new ItemStack(Material.STAINED_GLASS, 1, (short)8)),
	CYANSTAINEDGLASS("cyanglass", new ItemStack(Material.STAINED_GLASS, 1, (short)9)),
	PURPLESTAINEDGLASS("purpleglass", new ItemStack(Material.STAINED_GLASS, 1, (short)10)),
	BLUESTAINEDGLASS("blueglass", new ItemStack(Material.RED_ROSE, 1, (short)11)),
	BROWNSTAINEDGLASS("brownglass", new ItemStack(Material.STAINED_GLASS, 1, (short)12)),
	GREENSTAINEDGLASS("greenglass", new ItemStack(Material.STAINED_GLASS, 1, (short)13)),
	REDSTAINEDGLASS("redglass", new ItemStack(Material.STAINED_GLASS, 1, (short)14)),
	BLACKSTAINEDGLASS("blackglass", new ItemStack(Material.STAINED_GLASS, 1, (short)15)),
	WOODENTRAPDOOR("trapdoor", new ItemStack(Material.TRAP_DOOR)),
	STONEMONSTEREGG("stoneegg", new ItemStack(Material.MONSTER_EGGS)),
	COBBLESTONEMONSTEREGG("cobbleegg", new ItemStack(Material.MONSTER_EGGS, 1, (short)1)),
	STONEBRICKMONSTEREGG("stonebrickegg", new ItemStack(Material.MONSTER_EGGS, 1, (short)2)),
	MOSSYSTONEBRICKMONSTEREGG("mossybrickegg", new ItemStack(Material.MONSTER_EGGS, 1, (short)3)),
	CRACKEDSTONEBRICKMONSTEREGG("crackedbrickegg", new ItemStack(Material.MONSTER_EGGS, 1, (short)4)),
	CHISELEDSTONEBRICKMONSTEREGG("chiseledbrickegg", new ItemStack(Material.RED_ROSE, 1, (short)5)),
	STONEBRICKS("stonebrick", new ItemStack(Material.SMOOTH_BRICK)),
	MOSSYSTONEBRICKS("mossybrick", new ItemStack(Material.SMOOTH_BRICK, 1, (short)1)),
	CRACKEDSTONEBRICKS("crackedbrick", new ItemStack(Material.SMOOTH_BRICK, 1, (short)2)),
	CHISELEDSTONEBRICKS("chiseledbrick", new ItemStack(Material.SMOOTH_BRICK, 1, (short)3)),
	IRONBARS("bars", new ItemStack(Material.IRON_FENCE)),
	GLASSPANE("pane", new ItemStack(Material.THIN_GLASS)),
	MELONBLOCK("melonblock", new ItemStack(Material.MELON_BLOCK)),
	VINES("vine", new ItemStack(Material.VINE)),
	OAKFENCEGATE("fencegate", new ItemStack(Material.FENCE_GATE)),
	BRICKSTAIRS("brickstairs", new ItemStack(Material.BRICK_STAIRS)),
	STONEBRICKSTAIRS("stonestairs", new ItemStack(Material.SMOOTH_STAIRS)),
	MYCELIUM("mycelium", new ItemStack(Material.MYCEL)),
	LILYPAD("lilypad", new ItemStack(Material.WATER_LILY)),
	NETHERBRICK("netherbrick", new ItemStack(Material.NETHER_BRICK)),
	NETHERBRICKFENCE("netherbrickfence", new ItemStack(Material.NETHER_BRICK_STAIRS)),
	NETHERWART("wart", new ItemStack(Material.NETHER_WARTS)),
	ENCHANTMENTTABLE("enchantment", new ItemStack(Material.ENCHANTMENT_TABLE)),
	BREWINGSTAND("brewing", new ItemStack(Material.BREWING_STAND_ITEM)),
	CAULDRON("cauldron", new ItemStack(Material.CAULDRON_ITEM)),
	ENDPORTALFRAME("endportal", new ItemStack(Material.ENDER_PORTAL_FRAME)),
	ENDSTONE("endstone", new ItemStack(Material.ENDER_STONE)),
	DRAGONEGG("dragonegg", new ItemStack(Material.DRAGON_EGG)),
	OAKWOODSLAB("woodslab", new ItemStack(Material.WOOD_STEP)),
	SPRUCEWOODSLAB("spruceslab", new ItemStack(Material.WOOD_STEP, 1, (short)1)),
	BIRCHWOODSLAB("birchslab", new ItemStack(Material.WOOD_STEP, 1, (short)2)),
	JUNGLEWOODSLAB("jungleslab", new ItemStack(Material.WOOD_STEP, 1, (short)3)),
	ACACIAWOODSLAB("acaciaslab", new ItemStack(Material.WOOD_STEP, 1, (short)4)),
	DARKOAKWOODSLAB("darkoakslab", new ItemStack(Material.WOOD_STEP, 1, (short)5)),
	SANDSTONESTAIRS("sandstairs", new ItemStack(Material.SANDSTONE_STAIRS)),
	EMERALDORE("emeraldore", new ItemStack(Material.EMERALD_ORE)),
	ENDERCHEST("enderchect", new ItemStack(Material.ENDER_CHEST)),
	TRIPWIREHOOK("tripwirehook", new ItemStack(Material.TRIPWIRE_HOOK)),
	EMERALDBLOCK("emeraldblock", new ItemStack(Material.EMERALD_BLOCK)),
	SPRUCEWOODSTAIRS("sprucestairs", new ItemStack(Material.SPRUCE_WOOD_STAIRS)),
	BIRCHWOODSTAIRS("birchstairs", new ItemStack(Material.BIRCH_WOOD_STAIRS)),
	JUNGLEWOODSTAIRS("junglestairs", new ItemStack(Material.JUNGLE_WOOD_STAIRS)),
	COMMANDBLOCK("command", new ItemStack(Material.COMMAND)),
	BEACON("beacon", new ItemStack(Material.BEACON)),
	COBBLESTONEWALL("cobblewall", new ItemStack(Material.COBBLE_WALL)),
	MOSSYCOBBLESTONEWALL("mossywall", new ItemStack(Material.COBBLE_WALL, 1, (short)1)),
	FLOWERPOT("pot", new ItemStack(Material.FLOWER_POT_ITEM)),
	WOODENBUTTON("woodbutton", new ItemStack(Material.WOOD_BUTTON)),
	ANVIL("anvil", new ItemStack(Material.ANVIL)),
	TRAPPEDCHEST("trappedchest", new ItemStack(Material.TRAPPED_CHEST)),
	WEIGHTEDPRESSUREPLATE_LIGHT("goldplate", new ItemStack(Material.GOLD_PLATE)),
	WEIGHTEDPRESSUREPLATE_HEAVY("ironplate", new ItemStack(Material.IRON_PLATE)),
	DAYLIGHTSENSOR("daylightsensor", new ItemStack(Material.DAYLIGHT_DETECTOR)),
	REDSTONEBLOCK("redstoneblock", new ItemStack(Material.REDSTONE_BLOCK)),
	NETHERQUARTZORE("quartzore", new ItemStack(Material.QUARTZ_ORE)),
	HOPPER("hopper", new ItemStack(Material.HOPPER)),
	QUARTZBLOCK("quartzblock", new ItemStack(Material.QUARTZ_BLOCK)),
	CHISELEDQUARTZBLOCK("chiseledquartz", new ItemStack(Material.QUARTZ_BLOCK, 1, (short)1)),
	PILLARQUARTZBLOCK("quartzpillar", new ItemStack(Material.QUARTZ_BLOCK, 1, (short)2)),
	QUARTZSTAIRS("quartzstairs", new ItemStack(Material.QUARTZ_STAIRS)),
	ACTIVATORRAIL("activerail", new ItemStack(Material.ACTIVATOR_RAIL)),
	DROPPER("dropper", new ItemStack(Material.DROPPER)),
	WHITESTAINEDCLAY("stainedclay", new ItemStack(Material.STAINED_CLAY)),
	ORANGESTAINEDCLAY("orangeclay", new ItemStack(Material.STAINED_CLAY, 1, (short)1)),
	MAGENTASTAINEDCLAY("magentaclay", new ItemStack(Material.STAINED_CLAY, 1, (short)2)),
	LIGHTBLUESTAINEDCLAY("lightblueclay", new ItemStack(Material.STAINED_CLAY, 1, (short)3)),
	YELLOWSTAINEDCLAY("yellowclay", new ItemStack(Material.STAINED_CLAY, 1, (short)4)),
	LIMESTAINEDCLAY("limeclay", new ItemStack(Material.STAINED_CLAY, 1, (short)5)),
	PINKSTAINEDCLAY("pinkclay", new ItemStack(Material.STAINED_CLAY, 1, (short)6)),
	GRAYSTAINEDCLAY("greyclay", new ItemStack(Material.STAINED_CLAY, 1, (short)7)),
	LIGHTGRAYSTAINEDCLAY("lightgreyclay", new ItemStack(Material.STAINED_CLAY, 1, (short)8)),
	CYANSTAINEDCLAY("cyanclay", new ItemStack(Material.STAINED_CLAY, 1, (short)9)),
	PURPLESTAINEDCLAY("purpleclay", new ItemStack(Material.STAINED_CLAY, 1, (short)10)),
	BLUESTAINEDCLAY("blueclay", new ItemStack(Material.STAINED_CLAY, 1, (short)11)),
	BROWNSTAINEDCLAY("brownclay", new ItemStack(Material.STAINED_CLAY, 1, (short)12)),
	GREENSTAINEDCLAY("greenclay", new ItemStack(Material.STAINED_CLAY, 1, (short)13)),
	REDSTAINEDCLAY("redclay", new ItemStack(Material.STAINED_CLAY, 1, (short)14)),
	BLACKSTAINEDCLAY("blackclay", new ItemStack(Material.STAINED_CLAY, 1, (short)15)),
	WHITESTAINEDGLASSPANE("whitepane", new ItemStack(Material.STAINED_GLASS_PANE)),
	ORANGESTAINEDGLASSPANE("orangepane", new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)1)),
	MAGENTASTAINEDGLASSPANE("magentapane", new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)2)),
	LIGHTBLUESTAINEDPANE("lightbluepane", new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)3)),
	YELLOWSTAINEDGLASSPANE("yellowpane", new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)4)),
	LIMESTAINEDGLASSPANE("limepane", new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)5)),
	PINKSTAINEDGLASSPANE("pinkpane", new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)6)),
	GRAYSTAINEDGLASSPANE("greypane", new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)7)),
	LIGHTGRAYSTAINEDGLASSPANE("lightgreypane", new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)8)),
	CYANSTAINEDGLASSPANE("cyanpane", new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)9)),
	PURPLESTAINEDGLASSPANE("purplepane", new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)10)),
	BLUESTAINEDGLASSPANE("bluepane", new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)11)),
	BROWNSTAINEDGLASSPANE("brownpane", new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)12)),
	GREENSTAINEDGLASSPANE("greenpane", new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)13)),
	REDSTAINEDGLASSPANE("redpane", new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)14)),
	BLACKSTAINEDGLASSPANE("blackpane", new ItemStack(Material.STAINED_GLASS_PANE, 1, (short)15)),
	ACACIALEAVES("acacialeaves", new ItemStack(Material.LEAVES_2)),
	DARKOAKLEAVES("darkoakleaves", new ItemStack(Material.LEAVES_2, 1, (short)1)),
	ACACIAWOOD("acacia", new ItemStack(Material.LOG_2)),
	DARKOAKWOOD("darkoak", new ItemStack(Material.LOG_2, 1, (short)1)),
	ACACIAWOODSTAIRS("acaciastairs", new ItemStack(Material.ACACIA_STAIRS)),
	DARKOAKSTAIRS("darkoakstairs", new ItemStack(Material.DARK_OAK_STAIRS)),
	SLIMEBLOCK("slimeblock", new ItemStack(Material.SLIME_BLOCK)),
	BARRIER("barrier", new ItemStack(Material.BARRIER)),
	IRONTRAPDOOR("irontrapdoor", new ItemStack(Material.IRON_TRAPDOOR)),
	PRISMARINE("prismarine", new ItemStack(Material.PRISMARINE)),
	PRISMARINEBRICKS("prismarinebricks", new ItemStack(Material.PRISMARINE, 1, (short)1)),
	DARKPRISMARINE("darkprismarine", new ItemStack(Material.PRISMARINE, 1, (short)2)),
	SEALANTERN("sealantern", new ItemStack(Material.SEA_LANTERN)),
	HAYBALE("hay", new ItemStack(Material.HAY_BLOCK)),
	WHITECARPET("carpet", new ItemStack(Material.CARPET)),
	ORANGECARPET("orangecarpet", new ItemStack(Material.CARPET, 1, (short)1)),
	MAGENTACARPET("magentacarpet", new ItemStack(Material.CARPET, 1, (short)2)),
	LIGHTBLUECARPET("lightbluecarpet", new ItemStack(Material.CARPET, 1, (short)3)),
	YELLOWCARPET("yellowcarpet", new ItemStack(Material.CARPET, 1, (short)4)),
	LIMECARPET("limecarpet", new ItemStack(Material.CARPET, 1, (short)5)),
	PINKCARPET("pinkcarpet", new ItemStack(Material.CARPET, 1, (short)6)),
	GRAYCARPET("greycarpet", new ItemStack(Material.CARPET, 1, (short)7)),
	LIGHTGRAYCARPET("lightgreycarpet", new ItemStack(Material.CARPET, 1, (short)8)),
	CYANCARPET("cyancarpet", new ItemStack(Material.CARPET, 1, (short)9)),
	PURPLECARPET("purplecarpet", new ItemStack(Material.CARPET, 1, (short)10)),
	BLUECARPET("bluecarpet", new ItemStack(Material.CARPET, 1, (short)11)),
	BROWNCARPET("browncarpet", new ItemStack(Material.CARPET, 1, (short)12)),
	GREENCARPET("greencarpet", new ItemStack(Material.CARPET, 1, (short)13)),
	REDCARPET("redcarpet", new ItemStack(Material.CARPET, 1, (short)14)),
	BLACKCARPET("blackcarpet", new ItemStack(Material.CARPET, 1, (short)15)),
	HARDENEDCLAY("hardclay", new ItemStack(Material.HARD_CLAY)),
	BLOCKOFCOAL("coalblock", new ItemStack(Material.COAL_BLOCK)),
	PACKEDICE("packedice", new ItemStack(Material.PACKED_ICE)),
	SUNFLOWER("sunflower", new ItemStack(Material.DOUBLE_PLANT)),
	LILAC("lilac", new ItemStack(Material.DOUBLE_PLANT, 1, (short)1)),
	DOUBLETALLGRASS("doublegrass", new ItemStack(Material.DOUBLE_PLANT, 1, (short)2)),
	LARGEFERN("largefern", new ItemStack(Material.DOUBLE_PLANT, 1, (short)3)),
	ROSEBUSH("rosebush", new ItemStack(Material.DOUBLE_PLANT, 1, (short)4)),
	PEONY("peony", new ItemStack(Material.DOUBLE_PLANT, 1, (short)5)),
	REDSANDSTONE("redsandstone", new ItemStack(Material.RED_SANDSTONE)),
	CHISELEDREDSANDSTONE("chiseledredsandstone", new ItemStack(Material.RED_SANDSTONE, 1, (short)1)),
	SMOOTHREDSANDSTONE("smoothredsandstone", new ItemStack(Material.RED_SANDSTONE, 1, (short)2)),
	REDSANDSTONESTAIRS("redsandstairs", new ItemStack(Material.RED_SANDSTONE_STAIRS)),
	REDSANDSTONESLAB("redsandslab", new ItemStack(Material.DOUBLE_STONE_SLAB2)),
	SPRUCEFENCEGATE("sprucegate", new ItemStack(Material.SPRUCE_FENCE_GATE)),
	BIRCHFENCEGATE("birchgate", new ItemStack(Material.BIRCH_FENCE_GATE)),
	JUNGLEFENCEGATE("junglegate", new ItemStack(Material.JUNGLE_FENCE_GATE)),
	DARKOAKFENCEGATE("darkoakgate", new ItemStack(Material.DARK_OAK_FENCE_GATE)),
	ACACIAFENCEGATE("acaciagate", new ItemStack(Material.ACACIA_FENCE_GATE)),
	SPRUCEFENCE("sprucefence", new ItemStack(Material.SPRUCE_FENCE)),
	BIRCHFENCE("birchfence", new ItemStack(Material.BIRCH_FENCE)),
	JUNGLEFENCE("junglefence", new ItemStack(Material.JUNGLE_FENCE)),
	DARKOAKFENCE("darkoakfence", new ItemStack(Material.DARK_OAK_FENCE)),
	ACACIAFENCE("acaciafence", new ItemStack(Material.ACACIA_FENCE)),
	IRONSHOVEL("ironspade", new ItemStack(Material.IRON_SPADE)),
	IRONPICKAXE("ironpick", new ItemStack(Material.IRON_PICKAXE)),
	IRONAXE("ironaxe", new ItemStack(Material.IRON_AXE)),
	FLINTANDSTEEL("lighter", new ItemStack(Material.FLINT_AND_STEEL)),
	APPLE("apple", new ItemStack(Material.APPLE)),
	BOW("bow", new ItemStack(Material.BOW)),
	ARROW("arrow", new ItemStack(Material.ARROW)),
	COAL("coal", new ItemStack(Material.COAL)),
	CHARCOAL("charcoal", new ItemStack(Material.COAL, 1, (short)1)),
	DIAMOND("diamond", new ItemStack(Material.DIAMOND)),
	IRONINGOT("iron", new ItemStack(Material.IRON_INGOT)),
	GOLDINGOT("gold", new ItemStack(Material.GOLD_INGOT)),
	IRONSWORD("ironsword", new ItemStack(Material.IRON_SWORD)),
	WOODENSWORD("woodsword", new ItemStack(Material.WOOD_SWORD)),
	WOODENSHOVEL("woodspade", new ItemStack(Material.WOOD_SPADE)),
	WOODENPICKAXE("woodpick", new ItemStack(Material.WOOD_PICKAXE)),
	WOODENAXE("woodaxe", new ItemStack(Material.WOOD_AXE)),
	STONESWORD("stonesword", new ItemStack(Material.STONE_SWORD)),
	STONESHOVEL("stonespade", new ItemStack(Material.STONE_SPADE)),
	STONEPICKAXE("stonepick", new ItemStack(Material.STONE_PICKAXE)),
	STONEAXE("stoneaxe", new ItemStack(Material.STONE_AXE)),
	DIAMONDSWORD("diamondsword", new ItemStack(Material.DIAMOND_SWORD)),
	DIAMONDSHOVEL("diamondspade", new ItemStack(Material.DIAMOND_SPADE)),
	DIAMONDAXE("diamondaxe", new ItemStack(Material.DIAMOND_AXE)),
	STICK("stick", new ItemStack(Material.STICK)),
	BOWL("bowl", new ItemStack(Material.BOWL)),
	MUSHROOMSTEW("stew", new ItemStack(Material.MUSHROOM_SOUP)),
	GOLDENSWORD("goldsword", new ItemStack(Material.GOLD_SWORD)),
	GOLDENSHOVEL("goldspade", new ItemStack(Material.GOLD_SPADE)),
	GOLDENPICKAXE("goldpick", new ItemStack(Material.GOLD_PICKAXE)),
	GOLDENAXE("goldaxe", new ItemStack(Material.GOLD_AXE)),
	STRING("string", new ItemStack(Material.STRING)),
	FEATHER("feather", new ItemStack(Material.FEATHER)),
	GUNPOWDER("gunpowder", new ItemStack(Material.SULPHUR)),
	WOODENHOE("woodhoe", new ItemStack(Material.WOOD_HOE)),
	STONEHOE("stonehoe", new ItemStack(Material.STONE_HOE)),
	IRONHOE("ironhoe", new ItemStack(Material.IRON_HOE)),
	DIAMONDHOE("diamondhoe", new ItemStack(Material.DIAMOND_HOE)),
	GOLDENHOE("goldhoe", new ItemStack(Material.GOLD_HOE)),
	WHEATSEEDS("seed", new ItemStack(Material.SEEDS)),
	WHEAT("wheat", new ItemStack(Material.WHEAT)),
	BREAD("bread", new ItemStack(Material.BREAD)),
	LEATHERHELMET("leatherhelmet", new ItemStack(Material.LEATHER_HELMET)),
	LEATHERCHESTPLATE("leatherchestplate", new ItemStack(Material.LEATHER_CHESTPLATE)),
	LEATHERLEGGINGS("leatherleggings", new ItemStack(Material.LEATHER_LEGGINGS)),
	LEATHERBOOTS("leatherboots", new ItemStack(Material.LEATHER_BOOTS)),
	CHAINHELMET("chainhelmet", new ItemStack(Material.CHAINMAIL_HELMET)),
	CHAINCHESTPLATE("chainchestplate", new ItemStack(Material.CHAINMAIL_CHESTPLATE)),
	CHAINLEGGINGS("chainleggings", new ItemStack(Material.CHAINMAIL_LEGGINGS)),
	CHAINBOOTS("chainboots", new ItemStack(Material.CHAINMAIL_BOOTS)),
	IRONHELMET("ironhelmet", new ItemStack(Material.IRON_HELMET)),
	IRONCHESTPLATE("ironchestplate", new ItemStack(Material.IRON_CHESTPLATE)),
	IRONLEGGINGS("ironleggings", new ItemStack(Material.IRON_LEGGINGS)),
	IRONBOOTS("ironboots", new ItemStack(Material.IRON_BOOTS)),
	DIAMONDHELMET("diamondhelmet", new ItemStack(Material.DIAMOND_HELMET)),
	DIAMONDCHESTPLATE("diamondchestplate", new ItemStack(Material.DIAMOND_CHESTPLATE)),
	DIAMONDLEGGINGS("diamondleggings", new ItemStack(Material.DIAMOND_LEGGINGS)),
	DIAMONDBOOTS("diamondboots", new ItemStack(Material.DIAMOND_BOOTS)),
	GOLDENELMET("goldhelmet", new ItemStack(Material.GOLD_HELMET)),
	GOLDENCHESTPLATE("goldchestplate", new ItemStack(Material.GOLD_CHESTPLATE)),
	GOLDENLEGGINGS("goldleggings", new ItemStack(Material.GOLD_LEGGINGS)),
	GOLDENBOOTS("goldboots", new ItemStack(Material.GOLD_BOOTS)),
	FLINT("flint", new ItemStack(Material.FLINT)),
	RAWPORKCHOP("rawporkchop", new ItemStack(Material.PORK)),
	COOKEDPORKCHOP("porkchop", new ItemStack(Material.GRILLED_PORK)),
	PAINTING("painting", new ItemStack(Material.PAINTING)),
	GOLDENAPPLE("gapple", new ItemStack(Material.GOLDEN_APPLE)),
	ENCHANTEDGOLDENAPPLE("enchantedgapple", new ItemStack(Material.GOLDEN_APPLE, 1, (short)1)),
	SIGN("sign", new ItemStack(Material.SIGN)),
	OAKDOOR("door", new ItemStack(Material.WOOD_DOOR)),
	BUCKET("bucket", new ItemStack(Material.BUCKET)),
	WATERBUCKET("waterbucket", new ItemStack(Material.WATER_BUCKET)),
	LAVABUCKET("lavabucket", new ItemStack(Material.LAVA_BUCKET)),
	MINECART("minecart", new ItemStack(Material.MINECART)),
	SADDLE("saddle", new ItemStack(Material.SADDLE)),
	IRONDOOR("irondoor", new ItemStack(Material.IRON_DOOR)),
	REDSTONE("redstone", new ItemStack(Material.REDSTONE)),
	SNOWBALL("snowball", new ItemStack(Material.SNOW_BALL)),
	BOAT("boat", new ItemStack(Material.BOAT)),
	LEATHER("leather", new ItemStack(Material.LEATHER)),
	MILKBUCKET("milk", new ItemStack(Material.MILK_BUCKET)),
	BRICK("claybrick", new ItemStack(Material.CLAY_BRICK)),
	CLAYBALL("clay", new ItemStack(Material.CLAY_BALL)),
	SUGARCANES("sugarcane", new ItemStack(Material.SUGAR_CANE)),
	PAPER("paper", new ItemStack(Material.PAPER)),
	BOOK("book", new ItemStack(Material.BOOK)),
	SLIMEBALL("slimeball", new ItemStack(Material.SLIME_BALL)),
	MINECARTWITHCHEST("chestcart", new ItemStack(Material.STORAGE_MINECART)),
	MINECARTWITHFURNACE("furnacecart", new ItemStack(Material.POWERED_MINECART)),
	EGG("egg", new ItemStack(Material.EGG)),
	COMPASS("compass", new ItemStack(Material.COMPASS)),
	FISHINGROD("fishingrod", new ItemStack(Material.FISHING_ROD)),
	CLOCK("clock", new ItemStack(Material.WATCH)),
	GLOWSTONEDUST("glowstonedust", new ItemStack(Material.GLOWSTONE_DUST)),
	RAWFISH("fish", new ItemStack(Material.RAW_FISH)),
	RAWSALMON("salmon", new ItemStack(Material.RAW_FISH, 1, (short)1)),
	CLOWNFISH("clownfish", new ItemStack(Material.RAW_FISH, 1, (short)2)),
	PUFFERFISH("pufferfish", new ItemStack(Material.RAW_FISH, 1, (short)3)),
	COOKEDFISH("cookedfish", new ItemStack(Material.COOKED_FISH)),
	COOKEDSALMON("cookedsalmon", new ItemStack(Material.COOKED_FISH, 1, (short)1)),
	INKSAC("dye", new ItemStack(Material.INK_SACK)),
	ROSERED("reddye", new ItemStack(Material.INK_SACK, 1, (short)1)),
	CACTUSGREEN("greendye", new ItemStack(Material.INK_SACK, 1, (short)2)),
	COCOBEANS("coco", new ItemStack(Material.INK_SACK, 1, (short)3)),
	LAPISLAZULI("lapis", new ItemStack(Material.INK_SACK, 1, (short)4)),
	PURPLEDYE("purpledye", new ItemStack(Material.INK_SACK, 1, (short)5)),
	CYANDYE("cyandye", new ItemStack(Material.INK_SACK, 1, (short)6)),
	LIGHTGRAYDYE("lightgreydye", new ItemStack(Material.INK_SACK, 1, (short)7)),
	GRAYDYE("greydye", new ItemStack(Material.INK_SACK, 1, (short)8)),
	PINKDYE("pinkdye", new ItemStack(Material.INK_SACK, 1, (short)9)),
	LIMEDYE("limedye", new ItemStack(Material.INK_SACK, 1, (short)10)),
	DANDELIONYELLOW("yellowdye", new ItemStack(Material.INK_SACK, 1, (short)11)),
	LIGHTBLUEDYE("lightbluedye", new ItemStack(Material.INK_SACK, 1, (short)12)),
	MAGENTADYE("magentadye", new ItemStack(Material.INK_SACK, 1, (short)13)),
	ORANGEDYE("orangedye", new ItemStack(Material.INK_SACK, 1, (short)14)),
	BONEMEAL("bonemeal", new ItemStack(Material.INK_SACK, 1, (short)15)),
	BONE("bone", new ItemStack(Material.BONE)),
	SUGAR("sugar", new ItemStack(Material.SUGAR)),
	CAKE("cake", new ItemStack(Material.CAKE)),
	REDSTONEREPEATER("repeater", new ItemStack(Material.DIODE)),
	COOKIE("cookie", new ItemStack(Material.COOKIE)),
	MAP("map", new ItemStack(Material.EMPTY_MAP)),
	SHEARS("shears", new ItemStack(Material.SHEARS)),
	MELON("melon", new ItemStack(Material.MELON)),
	PUMPKINSEEDS("pumpkinseeds", new ItemStack(Material.PUMPKIN_SEEDS)),
	MELONSEEDS("melonseeds", new ItemStack(Material.MELON_SEEDS)),
	RAWBEEF("beef", new ItemStack(Material.RAW_BEEF)),
	STEAK("steak", new ItemStack(Material.COOKED_BEEF)),
	RAWCHICKEN("rawchicken", new ItemStack(Material.RAW_CHICKEN)),
	COOKEDCHICKEN("chicken", new ItemStack(Material.COOKED_CHICKEN)),
	ROTTENFLESH("flesh", new ItemStack(Material.ROTTEN_FLESH)),
	ENDERPEARL("enderpearl", new ItemStack(Material.ENDER_PEARL)),
	BLAZEROD("blazerod", new ItemStack(Material.BLAZE_ROD)),
	GHASTTEAR("ghasttear", new ItemStack(Material.GHAST_TEAR)),
	GOLDNUGGET("nugget", new ItemStack(Material.GOLD_NUGGET)),
	WOODENSLAB("woodenslab", new ItemStack(Material.WOOD_STEP)),
	POTION("potion", new ItemStack(Material.POTION)),
	GLASSBOTTLE("bottle", new ItemStack(Material.GLASS_BOTTLE)),
	SPIDEREYE("spidereye", new ItemStack(Material.SPIDER_EYE)),
	FERMENTEDSPIDEREYE("fermentedspidereye", new ItemStack(Material.FERMENTED_SPIDER_EYE)),
	BLAZEPOWDER("blazepowder", new ItemStack(Material.BLAZE_POWDER)),
	MAGMACREAM("magma", new ItemStack(Material.MAGMA_CREAM)),
	EYEOFENDER("eye", new ItemStack(Material.EYE_OF_ENDER)),
	GLISTERINGMELON("glisteringmelon", new ItemStack(Material.SPECKLED_MELON)),
	SPAWNCREEPER("creeper", new ItemStack(Material.MONSTER_EGG, 1, (short)50)),
	SPAWNSKELETON("skeleton", new ItemStack(Material.MONSTER_EGG, 1, (short)51)),
	SPAWNSPIDER("spider", new ItemStack(Material.MONSTER_EGG, 1, (short)52)),
	SPAWNZOMBIE("zombie", new ItemStack(Material.MONSTER_EGG, 1, (short)54)),
	SPAWNSLIME("slime", new ItemStack(Material.MONSTER_EGG, 1, (short)55)),
	SPAWNGHAST("ghast", new ItemStack(Material.MONSTER_EGG, 1, (short)56)),
	SPAWNPIGMAN("pigman", new ItemStack(Material.MONSTER_EGG, 1, (short)57)),
	SPAWNENDERMAN("enderman", new ItemStack(Material.MONSTER_EGG, 1, (short)58)),
	SPAWNCAVESPIDER("cavespider", new ItemStack(Material.MONSTER_EGG, 1, (short)59)),
	SPAWNSILVERFISH("silverfish", new ItemStack(Material.MONSTER_EGG, 1, (short)60)),
	SPAWNBLAZE("blaze", new ItemStack(Material.MONSTER_EGG, 1, (short)61)),
	SPAWNMAGMACUBE("magmacube", new ItemStack(Material.MONSTER_EGG, 1, (short)62)),
	SPAWNBAT("bat", new ItemStack(Material.MONSTER_EGG, 1, (short)65)),
	SPAWNWITCH("witch", new ItemStack(Material.MONSTER_EGG, 1, (short)66)),
	SPAWNENDERMITE("endermite", new ItemStack(Material.MONSTER_EGG, 1, (short)67)),
	SPAWNGUARDIAN("guardian", new ItemStack(Material.MONSTER_EGG, 1, (short)68)),
	SPAWNPIG("pig", new ItemStack(Material.MONSTER_EGG, 1, (short)90)),
	SPAWNSHEEP("sheep", new ItemStack(Material.MONSTER_EGG, 1, (short)91)),
	SPAWNCOW("cow", new ItemStack(Material.MONSTER_EGG, 1, (short)92)),
	SPAWNCHICKEN("chicken", new ItemStack(Material.MONSTER_EGG, 1, (short)93)),
	SPAWNSQUID("squid", new ItemStack(Material.MONSTER_EGG, 1, (short)94)),
	SPAWNWOLF("wolf", new ItemStack(Material.MONSTER_EGG, 1, (short)95)),
	SPAWNMOOSHROOM("mooshroom", new ItemStack(Material.MONSTER_EGG, 1, (short)96)),
	SPAWNOCELOT("ocelot", new ItemStack(Material.MONSTER_EGG, 1, (short)98)),
	SPAWNHORSE("horse", new ItemStack(Material.MONSTER_EGG, 1, (short)100)),
	SPAWNRABBIT("rabbit", new ItemStack(Material.MONSTER_EGG, 1, (short)101)),
	SPAWNVILLAGER("villager", new ItemStack(Material.MONSTER_EGG, 1, (short)120)),
	BOTTLEOENCHATING("xpbottle", new ItemStack(Material.EXP_BOTTLE)),
	FIRECHARGE("firecharge", new ItemStack(Material.FIREBALL)),
	BOOKANDQUILL("bookandquill", new ItemStack(Material.BOOK_AND_QUILL)),
	WRITTENBOOK("writtenbook", new ItemStack(Material.WRITTEN_BOOK)),
	EMERALD("emerald", new ItemStack(Material.EMERALD)),
	ITEMFRAME("itemframe", new ItemStack(Material.ITEM_FRAME)),
	CARROT("carrot", new ItemStack(Material.CARROT)),
	POTATO("potato", new ItemStack(Material.POTATO)),
	BAKEDPOTATO("bakedpotato", new ItemStack(Material.BAKED_POTATO)),
	POISONOUS("poisonouspotato", new ItemStack(Material.POISONOUS_POTATO)),
	GOLDENCARROT("goldencarrot", new ItemStack(Material.GOLDEN_CARROT)),
	MOBHEADSKELETON("skull", new ItemStack(Material.SKULL_ITEM)),
	MOBHEADWITHER("witherskull", new ItemStack(Material.SKULL_ITEM, 1, (short)1)),
	MOBHEADZOMBIE("zombiehead", new ItemStack(Material.SKULL_ITEM, 1, (short)2)),
	MOBHEADPLAYER("head", new ItemStack(Material.SKULL_ITEM, 1, (short)3)),
	MOBHEADCREEPER("creeperhead", new ItemStack(Material.SKULL_ITEM, 1, (short)4)),
	CARROTONASTICK("carrotstick", new ItemStack(Material.CARROT_STICK)),
	NETHERSTAR("netherstar", new ItemStack(Material.NETHER_STAR)),
	PUMPKINPIE("pie", new ItemStack(Material.PUMPKIN_PIE)),
	ROCKET("rocket", new ItemStack(Material.FIREWORK)),
	FIREWORKSTAR("fireworkstar", new ItemStack(Material.FIREWORK_CHARGE)),
	ENCHANTEDBOOK("enchantedbook", new ItemStack(Material.ENCHANTED_BOOK)),
	REDSTONECOMPARATOR("comparator", new ItemStack(Material.REDSTONE_COMPARATOR)),
	NETHERQUARTZ("quartz", new ItemStack(Material.QUARTZ)),
	MINECARTWITHTNT("tntcart", new ItemStack(Material.EXPLOSIVE_MINECART)),
	MINECARTWITHHOPPER("hoppercart", new ItemStack(Material.HOPPER_MINECART)),
	PRISMARINESHARD("shard", new ItemStack(Material.PRISMARINE_SHARD)),
	PRISMARINECRYSTALS("crystal", new ItemStack(Material.PRISMARINE_CRYSTALS)),
	RAWRABBIT("rawrabbit", new ItemStack(Material.RABBIT_HIDE)),
	COOKEDRABBIT("cookedrabbit", new ItemStack(Material.COOKED_RABBIT)),
	RABBITSTEW("rabbitstew", new ItemStack(Material.RABBIT_STEW)),
	RABBITSFOOT("rabbitfoot", new ItemStack(Material.RABBIT_FOOT)),
	RABBITHIDE("rabbithide", new ItemStack(Material.RABBIT_HIDE)),
	ARMORSTAND("armorstand", new ItemStack(Material.ARMOR_STAND)),
	IRONBARDING("ironhorsearmor", new ItemStack(Material.IRON_BARDING)),
	GOLDENBARDING("goldenhorsearmor", new ItemStack(Material.GOLD_BARDING)),
	DIAMONDBARDING("diamondhorsearmor", new ItemStack(Material.DIAMOND_BARDING)),
	LEAD("lead", new ItemStack(Material.LEASH)),
	NAMETAG("nametag", new ItemStack(Material.NAME_TAG)),
	MINECARTWITHCOMMAND("commandcart", new ItemStack(Material.COMMAND_MINECART)),
	RAWMUTTON("rawmutton", new ItemStack(Material.MUTTON)),
	COOKEDMUTTON("mutton", new ItemStack(Material.COOKED_MUTTON)),
	BANNER("banner", new ItemStack(Material.BANNER)),
	SPRUCEDOOR("sprucedoor", new ItemStack(Material.SPRUCE_DOOR_ITEM)),
	BIRCHDOOR("birchdoor", new ItemStack(Material.BIRCH_DOOR_ITEM)),
	JUNGLEDOOR("jungledoor", new ItemStack(Material.JUNGLE_DOOR_ITEM)),
	ACACIADOOR("acaciadoor", new ItemStack(Material.ACACIA_DOOR_ITEM)),
	DARKOAKDOOR("darkoakdoor", new ItemStack(Material.DARK_OAK_DOOR_ITEM)),
	THIRTEENDISC("13", new ItemStack(Material.GOLD_RECORD)),
	CATDISC("cat", new ItemStack(Material.GREEN_RECORD)),
	BLOCKSDISC("blocks", new ItemStack(Material.RECORD_3)),
	CHIRPDISC("chirp", new ItemStack(Material.RECORD_4)),
	FARDISC("far", new ItemStack(Material.RECORD_5)),
	MALLDISC("mall", new ItemStack(Material.RECORD_6)),
	MELLOHIDISC("mellohi", new ItemStack(Material.RECORD_7)),
	STALDISC("stal", new ItemStack(Material.RECORD_8)),
	STRADDISC("strad", new ItemStack(Material.RECORD_9)),
	WARDDISC("ward", new ItemStack(Material.RECORD_10)),
	ELEVENDISC("11", new ItemStack(Material.RECORD_11)),
	WAITDISC("wait", new ItemStack(Material.RECORD_12)),
	NOTHING("nothing", new ItemStack(Material.AIR));
	
	private String alias;
	private ItemStack is;
	
	Items(String alias, ItemStack is)
	{
		this.alias = alias;
		this.is = is;
	}
	
	public static String getAlias(Items item)
	{
		return item.alias;
	}
	
	public static ItemStack getItemStack(Items item)
	{
		return item.is;
	}
	
	public static ItemStack fromUserString(String itemname)
	{
		if (itemname != null)
		{
			for (Items item : Items.values())
			{
				if (itemname.equalsIgnoreCase(item.alias))
				{
					return item.is;
				}
			}
			return null;
		}
		return null;
	}
	
}
