package com.tevonetwork.tevoapi.Core;

public enum WorldProperty {

	ICESNOWMELT,
	CROPTRAMPLING,
	WATERDAMAGE,
	PHYSICS,
	TNTBLOCKDAMAGE,
	BLOCKREGEN,
	FALLDAMAGE,
	LAVADAMAGE,
	FIREDAMAGE,
	LIGHTNINGDAMAGE,
	DROWNDAMAGE,
	SUFFOCATIONDAMAGE,
	CONTACTDAMAGE,
	VOIDDAMAGE,
	EXPLODEDAMAGE,
	MOBDAMAGE,
	PVP,
	HUNGER,
	MINECRAFTDEATHMSGS,
	ROPELADDERS,
	CREEPERBLOCKDAMAGE,
	DRAGONBLOCKDAMAGE,
	FIREBALLBLOCKDAMAGE,
	ZOMBIEDOORDAMAGE,
	ENDERMENGRIEFING,
	WEATHERCHANGE,
	CHUNKSINRAM,
	LEAFDECAY,
	NATURALMOBSPAWN,
	BUILD,
	STAFFBUILD;
	
}
